Use ecommerce;

INSERT INTO account (account_firstname, account_middlename, account_lastname, account_type, account_email, account_password)
VALUES
    ('Emma', 'Rose', 'Brown', 1, 'emma@example.com', 'password123'), -- User
    ('Oliver', 'Jacob', 'Wilson', 2, 'oliver@example.com', 'password123'), -- Corporate
    ('Lily', 'Sophia', 'Martinez', 3, 'lily@example.com', 'password123'), -- Dealer
    ('Benjamin', 'James', 'Lee', 5, 'benjamin@example.com', 'password123'), -- Admin
    ('William', NULL, 'Taylor', 4, 'william@example.com', 'password123'), -- Employee
    ('Sophie', 'Grace', 'Walker', 4, 'sophie@example.com', 'password123'), -- Employee
    ('Jack', 'Noah', 'Hall', 4, 'jack@example.com', 'password123'), -- Employee
    ('Charlotte', 'Lily', 'Lewis', 4, 'charlotte@example.com', 'password123'), -- Employee
    ('Alexander', 'Logan', 'Harris', 4, 'alexander@example.com', 'password123'), -- Employee
    ('Isabella', 'Mia', 'King', 1, 'isabella@example.com', 'password123'), -- User
    ('Lucas', 'Leo', 'Evans', 4, 'lucas@example.com', 'password123'), -- Employee
    ('Amelia', 'Harper', 'Wright', 1, 'amelia@example.com', 'password123'), -- User
    ('Ethan', 'Matthew', 'Morris', 1, 'ethan@example.com', 'password123'), -- User
    ('Michael', 'David', 'Allen', 4, 'michael@example.com', 'password123'), -- Employee
    ('Ava', 'Sophia', 'Parker', 1, 'ava@example.com', 'password123'), -- User
    ('Jacob', 'Matthew', 'Turner', 1, 'jacob@example.com', 'password123'), -- User
    ('Emily', 'Grace', 'Scott', 1, 'emily@example.com', 'password123'), -- User
    ('Ryan', 'Oliver', 'Adams', 4, 'ryan@example.com', 'password123'), -- Employee
    ('Mia', 'Lily', 'Jenkins', 1, 'mia@example.com', 'password123'), -- User
    ('Daniel', 'William', 'Bennett', 2, 'daniel@example.com', 'password123'); -- Corporate


# ACCOUNT TYPES
INSERT INTO account_type (account_type)
VALUES ('user'),
       ('corporate'),
       ('dealer'),
       ('employee'),
       ('administrator');


# ADDRESS TYPE
INSERT INTO address_type(address_type)
VALUES ('home'),
       ('office'),
       ('work');


#PRICE TYPE
INSERT INTO price_type (price_type)
VALUES ('standard'),
       ('offer'),
       ('discounted'),
       ('callForPrice');

#Phone Type
INSERT INTO phone_type(`phone_type`)
VALUES ('mobile'),
       ('office'),
       ('work'),
       ('fax');

INSERT INTO product_category (product_category)
VALUES ('Default'),
       ('No Category'),
       ('Electronics'),
       ('Clothing'),
       ('Home and Garden'),
       ('Books'),
       ('Toys and Games');


INSERT INTO product_subcategory (product_category_id, product_subcategory)
VALUES (1, 'Default'),
       (2, 'No Category'),
       (3, 'Smartphones'),
       (3, 'Laptops'),
       (4, 'Men\'s Apparel'),
       (5, 'Women\'s Apparel'),
       (5, 'Furniture'),
       (5, 'Kitchenware'),
       (6, 'Fiction'),
       (6, 'Non-Fiction'),
       (6, 'Board Games'),
       (7, 'Outdoor Toys');


#COUNTRIES

INSERT INTO `countries` (`country_code`, `country_name`)
VALUES ('AF', 'Afghanistan'),
       ('AL', 'Albania'),
       ('DZ', 'Algeria'),
       ('AS', 'American Samoa'),
       ('AD', 'Andorra'),
       ('AO', 'Angola'),
       ('AI', 'Anguilla'),
       ('AQ', 'Antarctica'),
       ('AG', 'Antigua and Barbuda'),
       ('AR', 'Argentina'),
       ('AM', 'Armenia'),
       ('AW', 'Aruba'),
       ('AU', 'Australia'),
       ('AT', 'Austria'),
       ('AZ', 'Azerbaijan'),
       ('BS', 'Bahamas'),
       ('BH', 'Bahrain'),
       ('BD', 'Bangladesh'),
       ('BB', 'Barbados'),
       ('BY', 'Belarus'),
       ('BE', 'Belgium'),
       ('BZ', 'Belize'),
       ('BJ', 'Benin'),
       ('BM', 'Bermuda'),
       ('BT', 'Bhutan'),
       ('BO', 'Bolivia'),
       ('BA', 'Bosnia and Herzegovina'),
       ('BW', 'Botswana'),
       ('BV', 'Bouvet Island'),
       ('BR', 'Brazil'),
       ('IO', 'British Indian Ocean Territory'),
       ('BN', 'Brunei Darussalam'),
       ('BG', 'Bulgaria'),
       ('BF', 'Burkina Faso'),
       ('BI', 'Burundi'),
       ('KH', 'Cambodia'),
       ('CM', 'Cameroon'),
       ('CA', 'Canada'),
       ('CV', 'Cape Verde'),
       ('KY', 'Cayman Islands'),
       ('CF', 'Central African Republic'),
       ('TD', 'Chad'),
       ('CL', 'Chile'),
       ('CN', 'China'),
       ('CX', 'Christmas Island'),
       ('CC', 'Cocos (Keeling) Islands'),
       ('CO', 'Colombia'),
       ('KM', 'Comoros'),
       ('CD', 'Democratic Republic of the Congo'),
       ('CG', 'Republic of the Congo'),
       ('CK', 'Cook Islands'),
       ('CR', 'Costa Rica'),
       ('HR', 'Croatia (Hrvatska)'),
       ('CU', 'Cuba'),
       ('CY', 'Cyprus'),
       ('CZ', 'Czech Republic'),
       ('DK', 'Denmark'),
       ('DJ', 'Djibouti'),
       ('DM', 'Dominica'),
       ('DO', 'Dominican Republic'),
       ('TL', 'East Timor'),
       ('EC', 'Ecuador'),
       ('EG', 'Egypt'),
       ('SV', 'El Salvador'),
       ('GQ', 'Equatorial Guinea'),
       ('ER', 'Eritrea'),
       ('EE', 'Estonia'),
       ('ET', 'Ethiopia'),
       ('FK', 'Falkland Islands (Malvinas)'),
       ('FO', 'Faroe Islands'),
       ('FJ', 'Fiji'),
       ('FI', 'Finland'),
       ('FR', 'France'),
       ('FX', 'France, Metropolitan'),
       ('GF', 'French Guiana'),
       ('PF', 'French Polynesia'),
       ('TF', 'French Southern Territories'),
       ('GA', 'Gabon'),
       ('GM', 'Gambia'),
       ('GE', 'Georgia'),
       ('DE', 'Germany'),
       ('GH', 'Ghana'),
       ('GI', 'Gibraltar'),
       ('GG', 'Guernsey'),
       ('GR', 'Greece'),
       ('GL', 'Greenland'),
       ('GD', 'Grenada'),
       ('GP', 'Guadeloupe'),
       ('GU', 'Guam'),
       ('GT', 'Guatemala'),
       ('GN', 'Guinea'),
       ('GW', 'Guinea-Bissau'),
       ('GY', 'Guyana'),
       ('HT', 'Haiti'),
       ('HM', 'Heard and Mc Donald Islands'),
       ('HN', 'Honduras'),
       ('HK', 'Hong Kong'),
       ('HU', 'Hungary'),
       ('IS', 'Iceland'),
       ('IN', 'India'),
       ('IM', 'Isle of Man'),
       ('ID', 'Indonesia'),
       ('IR', 'Iran (Islamic Republic of)'),
       ('IQ', 'Iraq'),
       ('IE', 'Ireland'),
       ('IL', 'Israel'),
       ('IT', 'Italy'),
       ('CI', 'Ivory Coast'),
       ('JE', 'Jersey'),
       ('JM', 'Jamaica'),
       ('JP', 'Japan'),
       ('JO', 'Jordan'),
       ('KZ', 'Kazakhstan'),
       ('KE', 'Kenya'),
       ('KI', 'Kiribati'),
       ('KP', 'Korea, Democratic People''s Republic of'),
       ('KR', 'Korea, Republic of'),
       ('XK', 'Kosovo'),
       ('KW', 'Kuwait'),
       ('KG', 'Kyrgyzstan'),
       ('LA', 'Lao People''s Democratic Republic'),
       ('LV', 'Latvia'),
       ('LB', 'Lebanon'),
       ('LS', 'Lesotho'),
       ('LR', 'Liberia'),
       ('LY', 'Libyan Arab Jamahiriya'),
       ('LI', 'Liechtenstein'),
       ('LT', 'Lithuania'),
       ('LU', 'Luxembourg'),
       ('MO', 'Macau'),
       ('MK', 'North Macedonia'),
       ('MG', 'Madagascar'),
       ('MW', 'Malawi'),
       ('MY', 'Malaysia'),
       ('MV', 'Maldives'),
       ('ML', 'Mali'),
       ('MT', 'Malta'),
       ('MH', 'Marshall Islands'),
       ('MQ', 'Martinique'),
       ('MR', 'Mauritania'),
       ('MU', 'Mauritius'),
       ('YT', 'Mayotte'),
       ('MX', 'Mexico'),
       ('FM', 'Micronesia, Federated States of'),
       ('MD', 'Moldova, Republic of'),
       ('MC', 'Monaco'),
       ('MN', 'Mongolia'),
       ('ME', 'Montenegro'),
       ('MS', 'Montserrat'),
       ('MA', 'Morocco'),
       ('MZ', 'Mozambique'),
       ('MM', 'Myanmar'),
       ('NA', 'Namibia'),
       ('NR', 'Nauru'),
       ('NP', 'Nepal'),
       ('NL', 'Netherlands'),
       ('AN', 'Netherlands Antilles'),
       ('NC', 'New Caledonia'),
       ('NZ', 'New Zealand'),
       ('NI', 'Nicaragua'),
       ('NE', 'Niger'),
       ('NG', 'Nigeria'),
       ('NU', 'Niue'),
       ('NF', 'Norfolk Island'),
       ('MP', 'Northern Mariana Islands'),
       ('NO', 'Norway'),
       ('OM', 'Oman'),
       ('PK', 'Pakistan'),
       ('PW', 'Palau'),
       ('PS', 'Palestine'),
       ('PA', 'Panama'),
       ('PG', 'Papua New Guinea'),
       ('PY', 'Paraguay'),
       ('PE', 'Peru'),
       ('PH', 'Philippines'),
       ('PN', 'Pitcairn'),
       ('PL', 'Poland'),
       ('PT', 'Portugal'),
       ('PR', 'Puerto Rico'),
       ('QA', 'Qatar'),
       ('RE', 'Reunion'),
       ('RO', 'Romania'),
       ('RU', 'Russian Federation'),
       ('RW', 'Rwanda'),
       ('KN', 'Saint Kitts and Nevis'),
       ('LC', 'Saint Lucia'),
       ('VC', 'Saint Vincent and the Grenadines'),
       ('WS', 'Samoa'),
       ('SM', 'San Marino'),
       ('ST', 'Sao Tome and Principe'),
       ('SA', 'Saudi Arabia'),
       ('SN', 'Senegal'),
       ('RS', 'Serbia'),
       ('SC', 'Seychelles'),
       ('SL', 'Sierra Leone'),
       ('SG', 'Singapore'),
       ('SK', 'Slovakia'),
       ('SI', 'Slovenia'),
       ('SB', 'Solomon Islands'),
       ('SO', 'Somalia'),
       ('ZA', 'South Africa'),
       ('GS', 'South Georgia South Sandwich Islands'),
       ('SS', 'South Sudan'),
       ('ES', 'Spain'),
       ('LK', 'Sri Lanka'),
       ('SH', 'St. Helena'),
       ('PM', 'St. Pierre and Miquelon'),
       ('SD', 'Sudan'),
       ('SR', 'Suriname'),
       ('SJ', 'Svalbard and Jan Mayen Islands'),
       ('SZ', 'Eswatini'),
       ('SE', 'Sweden'),
       ('CH', 'Switzerland'),
       ('SY', 'Syrian Arab Republic'),
       ('TW', 'Taiwan'),
       ('TJ', 'Tajikistan'),
       ('TZ', 'Tanzania, United Republic of'),
       ('TH', 'Thailand'),
       ('TG', 'Togo'),
       ('TK', 'Tokelau'),
       ('TO', 'Tonga'),
       ('TT', 'Trinidad and Tobago'),
       ('TN', 'Tunisia'),
       ('TR', 'Turkey'),
       ('TM', 'Turkmenistan'),
       ('TC', 'Turks and Caicos Islands'),
       ('TV', 'Tuvalu'),
       ('UG', 'Uganda'),
       ('UA', 'Ukraine'),
       ('AE', 'United Arab Emirates'),
       ('GB', 'United Kingdom'),
       ('US', 'United States'),
       ('UM', 'United States minor outlying islands'),
       ('UY', 'Uruguay'),
       ('UZ', 'Uzbekistan'),
       ('VU', 'Vanuatu'),
       ('VA', 'Vatican City State'),
       ('VE', 'Venezuela'),
       ('VN', 'Vietnam'),
       ('VG', 'Virgin Islands (British)'),
       ('VI', 'Virgin Islands (U.S.)'),
       ('WF', 'Wallis and Futuna Islands'),
       ('EH', 'Western Sahara'),
       ('YE', 'Yemen'),
       ('ZM', 'Zambia'),
       ('ZW', 'Zimbabwe')
;